package in.ashokit.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.Data;

@Entity
@Data
public class Student {
	
	@Id
	private int id; // Auto-generated by database
	private String name;
	private String email;
	private int courseId;

}
